[package]
name = "compeydev/rusty-luau"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "AGPL-3.0"
exclude = ["tests/**", "examples/**", "**"]
include = ["lib/**", "LICENSE.md", "README.md", "wally.toml"]

[dependencies]
